name: tests-cart

on:
  pull_request:
    paths:
      - "cart/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd cart && npm i && npm run test:ci
