apiVersion: apps/v1
kind: Deployment
metadata:
  name: bodygarment-deployment
  labels:
    app: bodygarment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bodygarment
  template:
    metadata:
      labels:
        app: bodygarment
    spec:
      containers:
        - name: bodygarment
          image: mofasa101/bodygarment
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: POSTGRESQL_URI
              value: "postgresql+asyncpg://user:pass@bodygarment-postgresql-srv:5432/db"
            - name: NATS_URI
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: vton
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: bodygarment-srv
spec:
  selector:
    app: bodygarment
  ports:
    - name: bodygarment
      protocol: TCP
      port: 3000
      targetPort: 3000
