name: tests-garments

on:
  pull_request:
    paths:
      - "garments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd garments && npm i && npm run test:ci
